# Install Node.js
- name: Install Node.js
  apt:
    name: nodejs
    state: present
  register: nodejs_install
  ignore_errors: yes

# Debug Node.js installation
- name: Debug Node.js installation
  debug:
    msg: "Node.js installation status: {{ nodejs_install }}"
  when: nodejs_install.failed

# Install npm
- name: Install npm
  apt:
    name: npm
    state: present
  register: npm_install
  ignore_errors: yes

# Debug npm installation
- name: Debug npm installation
  debug:
    msg: "NPM installation status: {{ npm_install }}"
  when: npm_install.failed

# Clone application repository
- name: Clone application repository
  git:
    repo: "{{ nodejs_repo }}"
    dest: "{{ nodejs_app_path }}"
  register: repo_clone
  ignore_errors: yes

# Debug repository clone
- name: Debug repository clone
  debug:
    msg: "Repository clone status: {{ repo_clone }}"
  when: repo_clone.failed

# Install npm dependencies
- name: Install npm dependencies
  command: npm install
  args:
    chdir: "{{ nodejs_app_path }}"
  register: npm_install_dependencies
  ignore_errors: yes

# Debug npm dependencies installation
- name: Debug npm dependencies installation
  debug:
    msg: "NPM dependencies installation status: {{ npm_install_dependencies }}"
  when: npm_install_dependencies.failed

# Copy Node.js configuration
- name: Copy Node.js configuration
  template:
    src: config.json.j2
    dest: "{{ nodejs_app_path }}/config/config.json"
  notify:
    - Restart Node.js service

# Debug Node.js configuration copy
- name: Debug Node.js configuration copy
  debug:
    msg: "Node.js configuration file copied to {{ nodejs_app_path }}/config/config.json"

# Start Node.js application
- name: Start Node.js application
  command: npm start
  args:
    chdir: "{{ nodejs_app_path }}"
  register: nodejs_start
  ignore_errors: yes
  notify:
    - Restart Node.js service

# Debug Node.js application start
- name: Debug Node.js application start
  debug:
    msg: "Node.js application start status: {{ nodejs_start }}"
  when: nodejs_start.failed
