# k8s/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  DB_HOST: MTcyLjE5MS4xMzUuMjM5
  DB_USER: cm9vdA==
  DB_PASSWORD: QWRpdHlhQDg2MA==
  DB_NAME: dXNlcmRi
