# k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: default  # Replace with your namespace if different
spec:
  type: LoadBalancer  # This exposes the service externally, you might use ClusterIP for internal access only
  selector:
    app: myapp  # Should match the label used in your Deployment
  ports:
    - protocol: TCP
      port: 4330          # Port that the service exposes
      targetPort: 4330  # Port on the container that the service forwards traffic to
